name: Portfolio Deploy to Test
on:
  push:
    branches:
      - test
  workflow_dispatch:

env:
  WEB_PATH: ~/subsites/test.adamvromman.net
jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: yarn-${{ hashFiles('package.json') }}

      - name: Install dependencies
        run: yarn --ignore-scripts

      - name: 🏗️ create production build
        run: yarn build

      # Setup container with private SSH Key (used by rsync)
      - name: 🔑 Load private SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      # RSYNC
      - name: Deploy web files with rsync
        run: |
          rsync -azh --exclude assets/ --exclude train-world/live/ -e "ssh -o StrictHostKeyChecking=no" dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{env.WEB_PATH}}
